# Constants related to parameters


# Constants representing input parameter keys
class USER_PARAMS_consts:
    __slots__ = ()
    CMD = "cmd"
    ENDPOINT = "endpoint"
    CLUSTER = "cluster"
    ATTRIBUTE = "attribute"
    ATTR_TYPE = "attr_type"
    ATTR_VAL = "attr_val"
    CODE = "code"
    MIN_INTRVL = "min_interval"
    MAX_INTRVL = "max_interval"
    REPTBLE_CHG = "reportable_change"
    DIR = "dir"
    MANF = "manf"
    TRIES = "tries"
    EXPECT_REPLY = "expect_reply"
    ARGS = "args"
    STATE_ID = "state_id"
    STATE_ATTR = "state_attr"
    ALLOW_CREATE = "allow_create"
    EVENT_SUCCESS = "event_success"
    EVENT_FAIL = "event_fail"
    EVENT_DONE = "event_done"
    READ_BEFORE_WRITE = "read_before_write"
    READ_AFTER_WRITE = "read_after_write"
    WRITE_IF_EQUAL = "write_if_equal"
    OUTCSV = "csvout"
    CSVLABEL = "csvlabel"


class SERVICE_consts:
    __slots__ = ()
    ADD_GROUP = "ADD_GROUP"
    ADD_TO_GROUP = "ADD_TO_GROUP"
    ALL_ROUTES_AND_NEIGHBOURS = "ALL_ROUTES_AND_NEIGHBOURS"
    ATTR_READ = "ATTR_READ"
    ATTR_WRITE = "ATTR_WRITE"
    BACKUP = "BACKUP"
    BIND_GROUP = "BIND_GROUP"
    BIND_IEEE = "BIND_IEEE"
    CONF_REPORT = "CONF_REPORT"
    EZSP_ADD_KEY = "EZSP_ADD_KEY"
    EZSP_BACKUP = "EZSP_BACKUP"
    EZSP_CLEAR_KEYS = "EZSP_CLEAR_KEYS"
    EZSP_GET_CONFIG_VALUE = "EZSP_GET_CONFIG_VALUE"
    EZSP_GET_IEEE_BY_NWK = "EZSP_GET_IEEE_BY_NWK"
    EZSP_GET_KEYS = "EZSP_GET_KEYS"
    EZSP_GET_POLICY = "EZSP_GET_POLICY"
    EZSP_GET_TOKEN = "EZSP_GET_TOKEN"  # nosec
    EZSP_GET_VALUE = "EZSP_GET_VALUE"
    EZSP_SET_CHANNEL = "EZSP_SET_CHANNEL"
    EZSP_START_MFG = "EZSP_START_MFG"
    GET_GROUPS = "GET_GROUPS"
    GET_ROUTES_AND_NEIGHBOURS = "GET_ROUTES_AND_NEIGHBOURS"
    GET_ZLL_GROUPS = "GET_ZLL_GROUPS"
    HANDLE_JOIN = "HANDLE_JOIN"
    IEEE_PING = "IEEE_PING"
    LEAVE = "LEAVE"
    OTA_NOTIFY = "OTA_NOTIFY"
    REJOIN = "REJOIN"
    REMOVE_ALL_GROUPS = "REMOVE_ALL_GROUPS"
    REMOVE_FROM_GROUP = "REMOVE_FROM_GROUP"
    REMOVE_GROUP = "REMOVE_GROUP"
    SCAN_DEVICE = "SCAN_DEVICE"
    SINOPE = "SINOPE"
    UNBIND_COORDINATOR = "UNBIND_COORDINATOR"
    UNBIND_GROUP = "UNBIND_GROUP"
    ZCL_CMD = "ZCL_CMD"
    ZDO_FLOOD_PARENT_ANNCE = "ZDO_FLOOD_PARENT_ANNCE"
    ZDO_JOIN_WITH_CODE = "ZDO_JOIN_WITH_CODE"
    ZDO_SCAN_NOW = "ZDO_SCAN_NOW"
    ZDO_UPDATE_NWK_ID = "ZDO_UPDATE_NWK_ID"
    ZIGPY_DECONZ = "ZIGPY_DECONZ"
    ZNP_BACKUP = "ZNP_BACKUP"
    ZNP_NVRAM_BACKUP = "ZNP_NVRAM_BACKUP"
    ZNP_NVRAM_RESET = "ZNP_NVRAM_RESET"
    ZNP_NVRAM_RESTORE = "ZNP_NVRAM_RESTORE"
    ZNP_RESTORE = "ZNP_RESTORE"


# Constants representing internal parameters keys
class INTERNAL_PARAMS_consts:
    __slots__ = ()
    ALLOW_CREATE = "allow_create"
    ARGS = "args"
    ATTR_ID = "attr_id"
    ATTR_TYPE = "attr_type"
    ATTR_VAL = "attr_val"
    CLUSTER_ID = "cluster_id"
    CMD_ID = "cmd_id"
    CODE = "code"
    DIR = "dir"
    EP_ID = "endpoint_id"
    EVT_DONE = "event_done"
    EVT_FAIL = "event_fail"
    EVT_SUCCESS = "event_success"
    EXPECT_REPLY = "expect_reply"
    MANF = "manf"
    MAX_INTERVAL = "max_interval"
    MIN_INTERVAL = "min_interval"
    READ_AFTER_WRITE = "read_after_write"
    READ_BEFORE_WRITE = "read_before_write"
    REPORTABLE_CHANGE = "reportable_change"
    STATE_ATTR = "state_attr"
    STATE_ID = "state_id"
    TRIES = "tries"
    WRITE_IF_EQUAL = "write_if_equal"
    CSV_FILE = "csvfile"
    CSV_LABEL = "csvlabel"


INTERNAL_PARAMS = INTERNAL_PARAMS_consts()
USER_PARAMS = USER_PARAMS_consts()
SERVICES = SERVICE_consts()
