# Constants related to parameters


# Constants representing input parameter keys
P_CMD = "cmd"
P_ENDPOINT = "endpoint"
P_CLUSTER = "cluster"
P_ATTRIBUTE = "attribute"
P_ATTR_TYPE = "attr_type"
P_ATTR_VAL = "attr_val"
P_CODE = "code"
P_MIN_INTRVL = "min_interval"
P_MAX_INTRVL = "max_interval"
P_REPTBLE_CHG = "reportable_change"
P_DIR = "dir"
P_MANF = "manf"
P_TRIES = "tries"
P_EXPECT_REPLY = "expect_reply"
P_ARGS = "args"
P_STATE_ID = "state_id"
P_STATE_ATTR = "state_attr"
P_ALLOW_CREATE = "allow_create"
P_EVENT_SUCCESS = "event_success"
P_EVENT_FAIL = "event_fail"
P_EVENT_DONE = "event_done"
P_READ_BEFORE_WRITE = "read_before_write"
P_READ_AFTER_WRITE = "read_after_write"
P_WRITE_IF_EQUAL = "write_if_equal"
P_OUTCSV = "out_csv"


# Constants representing internal parameters keys
ALLOW_CREATE = "allow_create"
ARGS = "args"
ATTR_ID = "attr_id"
ATTR_TYPE = "attr_type"
ATTR_VAL = "attr_val"
CLUSTER_ID = "cluster_id"
CMD_ID = "cmd_id"
CODE = "code"
DIR = "dir"
EP_ID = "endpoint_id"
EVT_DONE = "event_done"
EVT_FAIL = "event_fail"
EVT_SUCCESS = "event_success"
EXPECT_REPLY = "expect_reply"
MANF = "manf"
MAX_INTERVAL = "max_interval"
MIN_INTERVAL = "min_interval"
READ_AFTER_WRITE = "read_after_write"
READ_BEFORE_WRITE = "read_before_write"
REPORTABLE_CHANGE = "reportable_change"
STATE_ATTR = "state_attr"
STATE_ID = "state_id"
TRIES = "tries"
WRITE_IF_EQUAL = "write_if_equal"
CSV_FILE = "csvfile"
