---
files: ^(.*\.(py|json|md|sh|yaml|cfg|txt))$
exclude: ^(\.[^/]*cache/.*|.*/_user.py)$
repos:
  - repo: https://github.com/executablebooks/mdformat
    # Do this before other tools "fixing" the line endings
    rev: 2d496dbc18e31b83a1596685347ffe0b6041daf0  # 1.0.0
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat  # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: [--wrap, '75', --number]
        additional_dependencies:
          - mdformat-toc
          - mdformat-beautysh
          - setuptools==84.0.0  # workaround for beautysh
          # -mdformat-shfmt
          # -mdformat-tables
          - mdformat-config
          - mdformat-black
          - mdformat-web
          - mdformat-gfm
  - repo: https://github.com/asottile/blacken-docs
    rev: dda8db18cfc68df532abf33b185ecd12d5b7b326  # 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==26.5.1]
        stages: [manual]  # Manual because already done by mdformat-black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^.*\.md$
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: check-json
      - id: check-builtin-literals
      - id: check-ast
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: check-case-conflict
      # - id: check-toml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea  # v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: https://github.com/adrienverge/yamllint.git
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # v1.38.0
    hooks:
      - id: yamllint
        args:
          - --no-warnings
          - -d
          - '{extends: relaxed, rules: {line-length: {max: 90}}}'
  - repo: https://github.com/lovesegfault/beautysh.git
    rev: 885128fe2600889194c69fa19326cf55a3462777  # v6.4.3
    hooks:
      - id: beautysh
        additional_dependencies:
          - setuptools==84.0.0  # workaround for beautysh
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a6564f5d57444e123433a5c9af733e3975c77229  # v0.11.0.1-1
    hooks:
      - id: shellcheck
        files: ^[^\.].*\.sh$
        # add "shellcheck disable=SC2086" codes to files, rather than global excludes:
        # args: [-x,-e2086,-e2004,-e2207,-e2002,-e2116]
        # args: ["--severity=warning"]  # Optionally only show errors and warnings
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 1f1e8bf348ff38fc88619a38d3ca4d9c56abea49  # v0.16.5
    hooks:
      # Note, added for future reference, not used
      - id: ruff
        stages: [manual]
      - id: ruff-format
        stages: [manual]
  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4  # v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/psf/black
    rev: 87928e6d6761a4a6d22250e1fee5601b3998086e  # 26.5.1
    hooks:
      - id: black
        args: [--safe, --quiet, -l 79]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: be256dab724687e8c3d7d6f52c1b263e2de6d439  # v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [--skip, 'B101,B311', --recursive, .]
  - repo: https://github.com/PyCQA/autoflake
    rev: 6d9dd2716540ab776f29c7b896cd3052ef4619b2  # v2.4.0
    hooks:
      - id: autoflake
        args: [-i, -r, --expand-star-imports, custom_components]
  - repo: https://github.com/PyCQA/flake8
    rev: d93590f5be797aabb60e3b09f2f52dddb02f349f  # 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          # - pyproject-flake8>=0.0.1a5
          - flake8-bugbear>=25.11.29
          - flake8-comprehensions>=3.17.0
          - flake8-2020>=1.8.1
          - mccabe>=0.7.0
          - pycodestyle>=2.14.0
          - pyflakes>=3.4.0
  - repo: https://github.com/PyCQA/isort
    rev: 131f4adcd5582bfc53928ab0d740eceb8b506b6c  # 9.0.1b5
    hooks:
      - id: isort
  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # v2.4.3
    hooks:
      - id: codespell
        args:
          # - --builtin=clear,rare,informal,usage,code,names,en-GB_to_en-US
          - --builtin=clear,rare,informal,usage,code,names
          - --ignore-words-list=hass,master
          - --skip="./.*"
          - --quiet-level=2
  - repo: https://github.com/pylint-dev/pylint
    rev: ecb84baf74ae152a511e5fdada5000c85250a48f  # v4.0.8
    hooks:
      - id: pylint
        args: [--reports=no, --py-version=3.10]
        additional_dependencies:
          - aiofiles>=25.1.0
          # - pylint-blocking-calls
          # - homeassistant-stubs>=2023.1.7
        # exclude: ^$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 7ff8d35ae36a7d2b968f2f90b4c723e292e594ee  # v2.3.1
    hooks:
      - id: mypy
        args:
          # - --verbose
          # - --config-file=setup.cfg
          - --ignore-missing-imports
          - --install-types
          - --non-interactive
          - --check-untyped-defs
          - --show-error-codes
          - --show-error-context
        additional_dependencies:
          - zigpy==0.61.0
          - types_aiofiles>=0.4.0
          - types_pytz>=2023.1
          # - cryptography==3.3.2  # Compatible/Available on cygwin
          #- homeassistant-stubs>=2023.1.7
          #- pydantic
